### PR TITLE
Rebase to upstream 69e0e54844ac8c2133854d5ab2a569f643786be6

### PR DESCRIPTION
**Pull request by alebedev87**
Upstream commit: https://github.com/kubernetes-sigs/external-dns/commit/69e0e54844ac8c2133854d5ab2a569f643786be6.

Purpose: to get https://github.com/kubernetes-sigs/external-dns/pull/2400 for ExternalDNS Operator's API (ability to specify `routerName`).

Carry patches:
```
d39e87e5 upstream rebase tag documentation
04827d52 update vendored files
17fdbd06 UPSTREAM: <carry>: Updating ose-external-dns images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/3dea8426481b269476342fc0a631273f32ce691e/images/ose-external-dns.yml
02b6041d UPSTREAM: <carry>: Add .ci-operator.yaml with base_root_image
80c4bda7 UPSTREAM: <carry>: openshift: OpenShift dockerfiles added
57c950ef UPSTREAM: <carry>: openshift: Add DOWNSTREAM_OWNERS
46f94890 Updating ose-external-dns images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/3dea8426481b269476342fc0a631273f32ce691e/images/ose-external-dns.yml
b89bce0f Add .ci-operator.yaml with base_root_image
ad3e0fa9 UPSTREAM: <carry>: openshift: OpenShift dockerfiles added
c4bedc30 UPSTREAM: <carry>: openshift: Add DOWNSTREAM_OWNERS
```

### CODE REVIEW

**Comment by rfredette** [comment]
It seems some of the carried commits are doubled? These all appear twice in the commit history:
```
46f94890 Updating ose-external-dns images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/3dea8426481b269476342fc0a631273f32ce691e/images/ose-external-dns.yml
b89bce0f Add .ci-operator.yaml with base_root_image
ad3e0fa9 UPSTREAM: <carry>: openshift: OpenShift dockerfiles added
c4bedc30 UPSTREAM: <carry>: openshift: Add DOWNSTREAM_OWNERS
```

**Comment by alebedev87** [comment]
@rfredette : thanks a lot, well seen!
Those were the empty commits, I think this was my `cherry-pick` conflict resolutions.
Removed.

**Comment by rfredette** [comment]
@alebedev87 thanks!
/lgtm

**Pull request merged**
