### PR TITLE
CFE-124: Rebase to upstream v0.10.1

### PR DESCRIPTION
**Pull request by Elbehery**
Process: 

1. Identify commits

```
git log --oneline --no-merges 35f2594745d6955625c47d7c46029cf1cb639154..openshift/master
```
where `35f259` is the most recent upstream commit

2. Create merge commit with openshift/master and upstream v1.8.4 as parent commits

```
$ git remote update # make sure we update our refs
$ git checkout v0.10.1 # upstream CoreDNS 1.8.4 commit tag
$ git checkout -b merge-tmp # create a branch to do our merge work from
$ git checkout openshift/master # we want to be at the tip of the openshift master branch when we run the next command
$ echo 'merge kubernetes-sigs/external-dns v0.10.1' | git commit-tree merge-tmp^{tree} -p HEAD -p merge-tmp -F - deadbeef12345678
$ git branch merge-0.10.1 deadbeef12345678 # create a new branch for the cherry-pick work
$ git checkout merge-0.10.1 # make sure we are on the proper branch

```

3. Cherry pick all necessary commits identified in step 1

```
46f94890 UPSTREAM: <carry>: Updating ose-external-dns images to be consistent with ART Reconciling with https://github.com/openshift/ocp-build-data/tree/3dea8426481b269476342fc0a631273f32ce691e/images/ose-external-dns.yml
b89bce0f UPSTREAM: <carry>: Add .ci-operator.yaml with base_root_image
ad3e0fa9 UPSTREAM: <carry>: openshift: OpenShift dockerfiles added
c4bedc30 UPSTREAM: <carry>: openshift: Add DOWNSTREAM_OWNERS
```

### CODE REVIEW

**Comment by rfredette** [comment]
@Elbehery it looks like the vendor directory needs an update. Hopefully if you run `go mod vendor` and commit the changes, it will be enough to fix the CI jobs

**Comment by Elbehery** [comment]
> @Elbehery it looks like the vendor directory needs an update. Hopefully if you run `go mod vendor` and commit the changes, it will be enough to fix the CI jobs

@rfredette I have ran `go mod vendor` and committed the changes in a separate commit. 
I ran `make build` and `make test` locally and everything is fine, yet the CI still fails 

/retest

**Pull request merged**
