### PR TITLE
Rebase to upstream v0.14.2

### PR DESCRIPTION
**Pull request by alebedev87**
Whys:

- https://github.com/kubernetes-sigs/external-dns/pull/3301 (https://issues.redhat.com/browse/RFE-4642)
- https://github.com/kubernetes-sigs/external-dns/pull/3560 (https://issues.redhat.com/browse/RFE-4642)
- https://github.com/kubernetes-sigs/external-dns/pull/3906 ([Rebase Epic comment](https://issues.redhat.com/browse/NE-1727?focusedId=25240202&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25240202))
- A lot of dependency bumps (including Kube API and golang)

Doc with a detailed analysis: [link](https://docs.google.com/document/d/1EbWTv_IiT7eQmCSCqOFBomX5tVvhNI2jmGxyADFNRgc).

Carry patches which were added on top of the upstream commits:

- [Vendor update](https://github.com/openshift/external-dns/pull/58/commits/d03b4fbe9c17325465fadbcb0818accdfecd6a20)
- [Golang update to match the upstream change to `1.22`](https://github.com/openshift/external-dns/pull/58/commits/a2406104e6e53f5f51379d1d5f5c8996c67235da)
- [Fix for the empty view error when creating CNAME and TXT records with Infoblox provider](https://github.com/openshift/external-dns/pull/58/commits/2e2fd63421db2aee97c4ddc344d8ea21ed370acd)

### CODE REVIEW

**Comment by alebedev87** [comment]
Test PR with the image pushed manually: https://github.com/openshift/external-dns-operator/pull/223.

**Comment by alebedev87** [comment]
The last commit amended with no changes to retrigger tests modified in https://github.com/openshift/release/pull/55189.

**Comment by alebedev87** [comment]
[New carry patch](https://github.com/openshift/external-dns/pull/58/commits/2e2fd63421db2aee97c4ddc344d8ea21ed370acd) was added to address the problem with the creation of CNAME and TXT records with Infoblox provider. The problem was [initially addressed by adding "default" as the default view](https://github.com/openshift/external-dns-operator/pull/223/commits/78510c29e45993d7f1d961adda62c97bafa88554) but then rethought and addressed as a patch. This carry patch won't need to be pushed upstream because the upstream has already moved the Infoblox provider to [a dedicated webhook repository](https://github.com/AbsaOSS/external-dns-infoblox-webhook) which didn't show the problem.
See also [the test PR with this carry patch](https://github.com/openshift/external-dns-operator/pull/224) which passed all the e2e tests.

**Comment by alebedev87** [comment]
/label px-approved

No TE needed for this feature, release notes are enough.

**Comment by melvinjoseph86** [comment]
Tested the pr using cluster bot, basic functionality is working. Hence approving from QE side.
/label qe-approved

**Pull request merged**
